services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app
    env_file:
        -   ".env"
    working_dir: /var/www/html
    networks:
      - laravel_network
    command: '/bin/bash -c "php artisan migrate && php artisan db:seed && php-fpm"'
    depends_on:
        - db
        - redis
        - rabbitmq_management

  horizon:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    env_file:
        -   ".env"
    container_name: laravel_horizon_app
    working_dir: /var/www/html
    networks:
      - laravel_network
    depends_on:
        - app
        - db
        - redis
        - rabbitmq_management
    command: '/bin/bash -c "php artisan horizon"'

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/data:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  rabbitmq_management:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password
    networks:
        - laravel_network
volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge
